<?php
echo $this->headScript()
    ->appendFile($this->basePath() . '/js/app/curso/excluirCurso.js')
    ->appendFile($this->basePath() . '/js/app/curso/addCurso.js')
    ->appendFile($this->basePath() . '/js/app/curso/index.js');


?>

<div id="msg" style="width: 40%; float:right" role="alert"></div>
<h1>Histórico</h1>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">


<button type="button" class="btn btn-primary " onclick="add()">Novo</button><br>
</<br>
<br>
<div id="testPrint">
    <div class="input-group " style="width: 40%">

        <input type="text" id="pesquisar" class="form-control global_filter" placeholder="Pesquisar ..."
               aria-describedby="basic-addon1">
        <span class="input-group-addon" id="basic-addon1"><span class="glyphicon glyphicon-search"></span></span>
    </div>


    <table id="tbCurso" class='display' style="width:100%;word-break:break-all">
        <thead>
        <tr>

            <th>Nome do Evento </th>
            <th>Data</th>
            <th style="width:15%;word-break:break-all">Contratante</th>
            <th style="width:15%;word-break:break-all">Vendedor</th>
            <th style="width:15%;word-break:break-all">Valor Total</th>
            <th>Opções</th>

        </tr>
        </thead>
    </table>


    <!-- Modal -->
</div>
<div id="dialogAdd">
</div>
<div id="dialogEdit">
</div>
<div id="dialogDel">

</div>
