

<div id="msg" style="width: 40%; float:right" role="alert"></div>
<h1>Histórico</h1>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <table id="tbEvento" class='display' style="width:100%;word-break:break-all">
        <thead>
        <tr>

            <th>Nome do Evento </th>
            <th>Data</th>
            <th style="width:15%;word-break:break-all">Contratante</th>
            <th style="width:15%;word-break:break-all">Vendedor</th>
            <th style="width:15%;word-break:break-all">Valor Total</th>
            <th>Opções</th>

        </tr>
        </thead>
    </table>


    <!-- Modal -->
</div>


</div>
