<h1>Adicionar Despesa</h1>
<br>

<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/style.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');


echo $this->headScript()
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',));

$form = $this->form;

$form->setAttribute('id','equipe');
echo $this->form()->openTag($form);
echo $this->FormRow($form->get('nome')) . '<br><br>';
echo $this->FormRow($form->get('funcao')) . '<br><br>';
echo $this->FormRow($form->get('cache'));
echo $this->form()->closeTag($form);


