<?php
/**
 * Created by PhpStorm.
 * User: jhon.carvalho
 * Date: 17/08/2017
 * Time: 11:06
 */

namespace Application\Controller;


use Zend\Mvc\Controller\AbstractActionController;

class EventoController extends AbstractActionController
{

    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
    
    public function addAction(){
        
    }
}